/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JToggleButton;
import memorygame.Card;

/**
 *
 * @author ivan.fernandezguinde
 */
public class MemoryGame extends javax.swing.JFrame {
    
    public static int ROWS = 3;
    public static int COLUMNS = 4;
    
    private Card[][] cards;
    private JToggleButton[]][] buttons;
    private Card lastCardSelected;
    private JToggleButton lastButtonSelected;
    private int score;

    /**
     * Creates new form MemoryGame
     */
    public MemoryGame() {
        initComponents();
        
        buttons = new JToggleButtons[ROWS][COLUMNS];
        
        buttons[0][0] = card1;
        buttons[0][1] = card2;
        buttons[0][2] = card3;
        buttons[0][3] = card4;
        buttons[1][0] = card5;
        buttons[1][1] = card6;
        buttons[1][2] = card7;
        buttons[1][3] = card8;
        buttons[2][0] = card9;
        buttons[2][1] = card10;
        buttons[2][2] = card11;
        buttons[2][3] = card12;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton7 = new javax.swing.JToggleButton();
        uppanel = new javax.swing.JPanel();
        uptext = new javax.swing.JLabel();
        downpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dificultade = new javax.swing.JComboBox<>();
        NovaPartidaButton = new javax.swing.JButton();
        SairButton = new javax.swing.JButton();
        centerpanel = new javax.swing.JPanel();
        card1 = new javax.swing.JToggleButton();
        card2 = new javax.swing.JToggleButton();
        card3 = new javax.swing.JToggleButton();
        card4 = new javax.swing.JToggleButton();
        card5 = new javax.swing.JToggleButton();
        card6 = new javax.swing.JToggleButton();
        card7 = new javax.swing.JToggleButton();
        card8 = new javax.swing.JToggleButton();
        card9 = new javax.swing.JToggleButton();
        card10 = new javax.swing.JToggleButton();
        card11 = new javax.swing.JToggleButton();
        card12 = new javax.swing.JToggleButton();

        jToggleButton7.setText("jToggleButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uptext.setText("puntos");
        uppanel.add(uptext);

        getContentPane().add(uppanel, java.awt.BorderLayout.NORTH);

        jLabel1.setText("Nivel:");
        downpanel.add(jLabel1);

        dificultade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinxelo", "Medio", "Dificil" }));
        downpanel.add(dificultade);

        NovaPartidaButton.setText("Nova Partida");
        downpanel.add(NovaPartidaButton);

        SairButton.setText("Sair");
        downpanel.add(SairButton);

        getContentPane().add(downpanel, java.awt.BorderLayout.SOUTH);

        card1.setMaximumSize(new java.awt.Dimension(200, 200));
        card1.setMinimumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout centerpanelLayout = new javax.swing.GroupLayout(centerpanel);
        centerpanel.setLayout(centerpanelLayout);
        centerpanelLayout.setHorizontalGroup(
            centerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerpanelLayout.createSequentialGroup()
                .addGroup(centerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerpanelLayout.createSequentialGroup()
                        .addComponent(card3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(card4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(centerpanelLayout.createSequentialGroup()
                        .addComponent(card7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(card8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(centerpanelLayout.createSequentialGroup()
                .addComponent(card9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(card12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        centerpanelLayout.setVerticalGroup(
            centerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerpanelLayout.createSequentialGroup()
                .addGroup(centerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(card5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(card6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(card8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(centerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(card9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(card10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(centerpanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoryGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NovaPartidaButton;
    private javax.swing.JButton SairButton;
    private javax.swing.JToggleButton card1;
    private javax.swing.JToggleButton card10;
    private javax.swing.JToggleButton card11;
    private javax.swing.JToggleButton card12;
    private javax.swing.JToggleButton card2;
    private javax.swing.JToggleButton card3;
    private javax.swing.JToggleButton card4;
    private javax.swing.JToggleButton card5;
    private javax.swing.JToggleButton card6;
    private javax.swing.JToggleButton card7;
    private javax.swing.JToggleButton card8;
    private javax.swing.JToggleButton card9;
    private javax.swing.JPanel centerpanel;
    private javax.swing.JComboBox<String> dificultade;
    private javax.swing.JPanel downpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JPanel uppanel;
    private javax.swing.JLabel uptext;
    // End of variables declaration//GEN-END:variables
}
