/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg5.pkg1;

/**
 *
 * @author ivan.fernandezguinde
 */
public class HelloWorldGUI extends javax.swing.JFrame {

    /**
     * Creates new form HelloWorldGUI
     */
    public HelloWorldGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDeFondo = new javax.swing.JPanel();
        botonSaudo = new javax.swing.JButton();
        cuadroTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDeFondo.setBackground(new java.awt.Color(51, 153, 255));
        panelDeFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSaudo.setFont(new java.awt.Font("Laksaman", 0, 13)); // NOI18N
        botonSaudo.setText("Pulsame");
        botonSaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSaudoActionPerformed(evt);
            }
        });
        panelDeFondo.add(botonSaudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        cuadroTexto.setFont(new java.awt.Font("Likhan", 0, 13)); // NOI18N
        cuadroTexto.setForeground(new java.awt.Color(255, 0, 0));
        cuadroTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelDeFondo.add(cuadroTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDeFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDeFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSaudoActionPerformed
        cuadroTexto.setText("Hola Mundo");
    }//GEN-LAST:event_botonSaudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelloWorldGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelloWorldGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelloWorldGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelloWorldGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelloWorldGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSaudo;
    private javax.swing.JLabel cuadroTexto;
    private javax.swing.JPanel panelDeFondo;
    // End of variables declaration//GEN-END:variables
}
